apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${name: my-name}
  labels:
    name: ${name: my-name}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: ${name: my-name}
    spec:
      containers:
      - image: ${image: ipedrazas/docmock}
        name: ${name: my-name}
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name: ${ENVVARNAME: ENVVARNAME}
          value: ${ENVVARVALUE: ENVVARVALUE}       
        ports:
        - containerPort: ${port: 5000}
          name: ${name: my-name}
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always